### ISSUE TITLE
As a website visitor, I want to see Julien's profile on the member page.

### ISSUE THREAD

**Issue by Endlessflow** [ClubCedille/cedille.etsmtl.ca#142]
## Context
Julien's information is not currently displayed on the member page, making it difficult for visitors to know of his belonging to the club and potentially connect with him on professional networks.

## Acceptance Criteria
- [ ] Julien' information are added to the `equipe.yml` file. This includes:
  - Full Name
  - GitHub profile link
  - LinkedIn profile link
  - _[Optional] Profile picture path (i.e. `images/membres/{picturename}`)_
- [ ] _[Optional] The profile picture is properly sized to 225x225 pixels._

**Comment by SonOfLope** [comment]
completed last week in some pr
