### ISSUE TITLE
Refactoriser le contenu équipe pour qu'il provienne de contenu/equipe/equipe.md

### ISSUE THREAD

**Issue by SonOfLope** [ClubCedille/cedille.etsmtl.ca#20]
Le contenu de la page membre doit être obtenu à partir de fichier markdown (.md ou .yml) dans le repertoire Content.
En ce moment, il faut aller modifier le nom, prenom et liens github/linkedin directement dans un fichier html ce qui ne respecte pas la methodologie de Hugo.

Ressource : 
- Un exemple de site web dont le contenu est obtenu à partir du repertoire /contenu : 
    - https://jamstackthemes.dev/demo/theme/hugo-cohub/ (Voir la section About et scrolldown a la section "Our Angel Investors". Ce contenu est obtenu a partir du fichier yml suivant :
     [exampleSite/data/investor.yml](https://github.com/StaticMania/hugo-cohub/tree/master/exampleSite/data/investor.yml)
- [markdown-cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by bayes-diarra** [comment]
J'ai pas bien compris Jo
