### ISSUE TITLE
Ajuster la position des éléments lorsqu'on réduit la taille des pages web.

### ISSUE THREAD

**Issue by EdvinHonda** [ClubCedille/cedille.etsmtl.ca#22]
- Les 3 cartes de la page daccueil :
![image](https://user-images.githubusercontent.com/73133692/181500600-32323398-cf83-4577-8f49-e52f7e90c9cd.png)

La taille des 3 cartes devraient être égal : 
![image](https://user-images.githubusercontent.com/73133692/181500718-26aabe66-4c47-4b7d-8fcb-614d4a8d9464.png)

Centré la carte "souhaitez vous faire un don" : 
![image](https://user-images.githubusercontent.com/73133692/181500833-c54256c2-d9d2-4a03-840f-90831bc8c56e.png)

**Comment by bayes-diarra** [comment]
Dans le premier point tu veux qu'on mette de l'espace entre les cards si je comoprends bien?
